### ISSUE TITLE
debug output shows weird value from get()

### ISSUE THREAD

**Issue by ppine7** [fppt/jedis-mock#11]
Hi, 
I'm using embedded redis server in a unit test that increments a counter, and then gets the value using the jedis.get(counterName) command.
All works fine, but the debug output from the jedismock is weird:

It correctly shows expected response from the incr() command (the new value of the counter)
but it prepends "$1" prefix tot he value returned fromt he get() command :) - see examples below:

In this case the correct value of the counter is "5":
10:02:23.126 [Thread-1] DEBUG com.github.fppt.jedismock.Response - Received command [incr] sending reply _[:5]_
10:02:23.127 [Thread-1] DEBUG com.github.fppt.jedismock.Response - Received command [get] sending reply _**[$15]**_

In this case the correct value of the counter is "1":
10:02:23.135 [Thread-3] DEBUG com.github.fppt.jedismock.Response - Received command [incr] sending reply **[:1]**
10:02:23.136 [Thread-3] DEBUG com.github.fppt.jedismock.Response - Received command [get] sending reply **[$11]**

Thank you!!!

**Comment by fppt** [comment]
Hi! 

Thanks for your interest in the project. First of all let me ask, are the returned values what you expect? I.e. are incr and get returning the correct values, because they should be if not then you may have found a bug which I need to attend to.

Now let me explain the log lines. The log lines are showing what "encoded" responses are being sent back. With `incr`an integer is being sent back as shown [here](https://github.com/fppt/jedis-mock/blob/master/src/main/java/com/github/fppt/jedismock/Response.java#L39) with `get` a string is being sent back as shown [here](https://github.com/fppt/jedis-mock/blob/master/src/main/java/com/github/fppt/jedismock/Response.java#L28). 

You can see that the encodings for strings and ints are different. This is required by the redis protocol which is defined [here](https://redis.io/topics/protocol). In other words jedis clients expect bulk strings to be prepended with `$x` where `x` is the number of characters in the string. That's why the string `5` (gets returns strings in the mocks case) has an encoding of `$15`. Knowing the returned encoding is useful for me while I dev this tool. Hence the confusing debug line. I will try to make that clearer in the next release.

Does that help?

**Comment by fppt** [comment]
Cool. Glad that explanation made sense. Thanks for the question and for using the project. I am going to close this issue. If you have any other questions/concerns/suggestions please feel to create another issue.
